import { createStorage } from 'wagmi'
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
import { mainnet, arbitrum, base, polygon } from '@reown/appkit/networks'
import type { Chain } from 'viem'

// Read Project ID from environment variables
export const projectId = import.meta.env.VITE_WALLETCONNECT_PROJECT_ID || import.meta.env.VITE_PROJECT_ID

// Ensure Project ID is defined
if (!projectId) {
  console.warn('VITE_WALLETCONNECT_PROJECT_ID or VITE_PROJECT_ID is not defined. Please set it in .env file')
}

// Define supported networks
export const networks: [Chain, ...Chain[]] = [mainnet, arbitrum, base, polygon]

// Create the Wagmi adapter instance
// Note: Project ID is required for WalletConnect to work properly
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage(),
  ssr: false, // Vite doesn't need SSR
  projectId: projectId || '', // Empty string as fallback (will show warning)
  networks,
})

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig

